L = [5, 7, 2, 9, 4, 1, 3]
# len = len(L)
print("tamanho da lista: ", len(L))
print("menor valor: ", min(L))
print("maior valor: ", max(L))
print("soma total", sum(L))
L.sort()
print("ordem crescente: ", L)
L.reverse()
print("ordem decrescente: ", L)
